
platform :ios, '8.0'

target 'cabin' do
  pod 'AFNetworking', '~> 3.0'
  pod 'gRPC', '~> 1.9.1'
  pod 'Google'
  pod 'GoogleSignIn'
  pod 'Helm', :path => '.'
  pod 'NVHTarGzip'
  pod 'YAMLThatWorks'
end
