
platform :ios, '8.0'

target 'skippbox' do
  pod 'AFNetworking', '~> 3.0'
  pod 'gRPC', '~> 1.0.1-pre1'
  pod 'Google'
  pod 'GoogleSignIn'
  pod 'Helm', :path => '.'
  pod 'NVHTarGzip'
  pod 'YAMLThatWorks'
end
