export default {
  Status: {
    RUNNING: 'RUNNING',
    CHECKING: 'CHECKING',
    PENDING: 'PENDING',
    DOWN: 'DOWN',
    UNAUTHORIZED: 'UNAUTHORIZED',
    CONTAINERCREATING: 'CONTAINERCREATING',
    TERMINATING: 'TERMINATING',
    READY: 'READY',
    NOTREADY: 'NOTREADY',
    READY_UNSCHEDULABLE: 'READY_UNSCHEDULABLE',
  },
};
